#!/usr/bin/env python3
"""Sync TraceFence Sentinel metadata, screenshots, and App Review submission."""

from __future__ import annotations

import argparse
import base64
import hashlib
import json
import os
import sys
import time
from pathlib import Path
from typing import Any

import requests
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec, utils


APP_ID = "6789015094"
KEY_ID = "JHKYSFS5HM"
ISSUER_ID = "69a6de85-f729-47e3-e053-5b8c7c11a4d1"
VERSION = "1.0.0"
BUILD = os.environ.get("TRACEFENCE_SENTINEL_BUILD", "23")
PRIVACY_URL = "https://ai-scarlett.github.io/TraceFence/privacy-policy.html"
SUPPORT_URL = "https://ai-scarlett.github.io/TraceFence/support.html"
ROOT = Path(__file__).resolve().parents[2]
SCREENSHOT_DIR = ROOT / "build/TraceFenceSentinel-AppStore-Screenshots/en-US/APP_IPHONE_67"
PAIRING_DEMO_VIDEO_URL = os.environ.get("TRACEFENCE_PAIRING_DEMO_VIDEO_URL", "").strip()

REVIEW_NOTES = """TraceFence Sentinel is a free iPhone companion for a user-owned TraceFence Mac installation. It does not require an account and does not use a TraceFence cloud relay.

Review without a Mac:
1. On the first screen, tap "View Read-only Demo".
2. The demo provides local bundled data for Overview, Monitor, Sessions, Approvals, and Settings.
3. The demo is intentionally read-only and does not send network requests or control a Mac.

Real use:
- The user pairs a Mac by scanning or pasting an authenticated endpoint generated by the TraceFence Mac app.
- Build 23 accepts the compact TF pairing QR used by TraceFence Mac build 74 and remains compatible with legacy JSON pairing codes.
- Build 23 keeps probing the paired Mac's foreground and background gateways when one stale endpoint rejects an old token, preventing intermittent disconnects during app upgrades or token synchronization.
- Local access uses the same LAN. Remote access can use an existing private network path that the user configures independently on both devices.
- The app monitors the user's local AI-agent sessions and sends authenticated pause, resume, stop, instruction, and approval requests to the paired Mac.
- Notification permission is requested only after the user taps Allow Notifications in Settings.
- Camera access is used only to scan a pairing QR code. Face ID, Touch ID, or the device passcode protects app access and Mac pairing.

VPN clarification requested by App Review:
- TraceFence Sentinel does not contain VPN functionality. It does not create or manage a VPN, install a Network Extension, route device traffic, inspect network packets, or collect information through a VPN.
- The app collects no user information using VPN functionality because no such functionality exists. It uses ordinary URLSession requests to the paired Mac over the network path already selected by iOS.
- If a user independently configures a third-party private network, iOS may route the same token-authenticated Mac connection over that existing path. TraceFence neither reads that provider's configuration or credentials nor receives unrelated traffic.
- No pairing, Agent, prompt, project, command, or network data is shared with TraceFence or any third party. There is no TraceFence backend or cloud storage. Connection details remain in the iOS app container, and Agent/session data remains on the user's iPhone and Mac.

No ads, analytics, tracking, developer-accessible account data, or third-party telemetry are included. Agent prompts, command output, project paths, and pairing credentials remain on the user's devices. The iPhone app is free; any TraceFence subscription is purchased and managed in the corresponding Mac distribution channel."""

if PAIRING_DEMO_VIDEO_URL:
    REVIEW_NOTES += f"\n\nPhysical iPhone + Mac pairing and interaction demo (Mac build 74 / iOS build 23):\n{PAIRING_DEMO_VIDEO_URL}"

LOCALES: dict[str, dict[str, str]] = {
    "en-US": {
        "name": "TraceFence Sentinel",
        "subtitle": "Remote Agent Control",
        "promotionalText": "Monitor AI-agent work on your Mac, review approvals, and control supported sessions from your iPhone.",
        "description": """TraceFence Sentinel turns your iPhone into a private control console for AI agents running on your Mac.

Pair it directly with a user-owned TraceFence Mac installation to see current projects and sessions, review the latest conversation context, receive local alerts, approve sensitive commands, and control supported agent runtimes.

Key capabilities:
- Monitor installed and detected AI agents by agent and project
- View the latest session for each project and recent no-project sessions
- Review recent conversation context and task state
- Send follow-up instructions to controllable sessions
- Pause, resume, take over, or terminate supported tasks
- Approve or deny permission and command requests
- Receive local notifications for approvals, replies, and completion
- Reconnect using saved Mac endpoints when local addresses change
- Use Face ID, Touch ID, or device passcode protection

Privacy and connectivity:
- No TraceFence account or cloud relay
- No ads, tracking, or third-party analytics
- Direct token-authenticated connection to your Mac
- Same-LAN access works locally
- Remote access can use an existing private network path you configure independently

A TraceFence Mac installation is required for real monitoring and control. A built-in read-only demo is available before pairing.""",
        "keywords": "AI agent,Mac,Codex,Claude,remote control,approval,monitor,session,developer,privacy",
    },
    "zh-Hans": {
        "name": "TraceFence Sentinel",
        "subtitle": "远程 Agent 控制台",
        "promotionalText": "在 iPhone 上监控 Mac 的 AI Agent 任务、处理审批并控制受支持的会话。",
        "description": """TraceFence Sentinel 将 iPhone 变成 Mac 上 AI Agent 的私密控制台。

与用户自己的 TraceFence Mac 客户端直接配对后，你可以查看当前项目和会话、最近的对话上下文、审批敏感命令，并控制受支持的 Agent 运行时。

主要功能：
- 按 Agent 和项目监控本机任务
- 每个项目仅展示最新会话，并保留近期无项目会话
- 查看最近对话上下文与任务状态
- 向可控会话发送后续指令
- 暂停、继续、接管或终止受支持的任务
- 批准或拒绝权限与命令请求
- 接收审批、新回复和任务完成的本地通知
- Mac 地址变化后尝试已保存的连接记录
- 使用面容 ID、触控 ID 或设备密码保护

隐私与连接：
- 无 TraceFence 账号和云端中继
- 无广告、追踪或第三方分析
- 使用配对令牌直接连接 Mac
- 同一局域网可直接使用
- 远程访问可使用你自行配置的现有私有网络

真实监控和控制需要安装 TraceFence Mac 客户端；未配对前可以使用内置只读演示。""",
        "keywords": "AI Agent,Mac,Codex,Claude,远程控制,审批,监控,会话,开发者,隐私",
    },
    "zh-Hant": {
        "name": "TraceFence Sentinel",
        "subtitle": "遠端 Agent 控制台",
        "promotionalText": "在 iPhone 監控 Mac 的 AI Agent 工作、處理審批並控制支援的工作階段。",
        "description": """TraceFence Sentinel 將 iPhone 變成 Mac 上 AI Agent 的私密控制台。

與使用者自己的 TraceFence Mac App 直接配對後，可查看目前專案與工作階段、最近對話內容、審批敏感指令，並控制支援的 Agent 執行環境。

主要功能：
- 依 Agent 與專案監控本機工作
- 每個專案只顯示最新工作階段，並保留近期無專案工作階段
- 查看最近對話內容與工作狀態
- 向可控工作階段傳送後續指令
- 暫停、繼續、接管或終止支援的工作
- 批准或拒絕權限與指令請求
- 接收審批、新回覆及完成狀態的本機通知
- Mac 位址改變後嘗試已儲存的連線記錄
- 使用 Face ID、Touch ID 或裝置密碼保護

無 TraceFence 帳號、雲端中繼、廣告、追蹤或第三方分析。區域網路可直接使用；遠端連線可使用你自行設定的現有私人網路。

真實監控與控制需要 TraceFence Mac App；配對前可使用內建唯讀示範。""",
        "keywords": "AI Agent,Mac,Codex,Claude,遠端控制,審批,監控,工作階段,開發者,隱私",
    },
    "ja": {
        "name": "TraceFence Sentinel",
        "subtitle": "リモート Agent 操作",
        "promotionalText": "Mac 上の AI Agent を監視し、承認と対応セッションの操作を iPhone から行えます。",
        "description": """TraceFence Sentinel は、Mac で動作する AI Agent のためのプライベートな iPhone コントロールコンソールです。

ユーザー自身の TraceFence Mac App と直接ペアリングし、プロジェクトとセッション、最近の会話コンテキスト、権限リクエストを確認できます。対応するランタイムでは指示送信、一時停止、再開、引き継ぎ、終了も行えます。

TraceFence のアカウント、クラウド中継、広告、トラッキング、第三者分析はありません。同じ LAN では直接接続し、リモート接続にはユーザーが別途設定した既存のプライベートネットワークを利用できます。

実際の監視と操作には TraceFence Mac App が必要です。ペアリング前には内蔵の読み取り専用デモを利用できます。""",
        "keywords": "AI Agent,Mac,Codex,Claude,遠隔操作,承認,監視,セッション,開発,プライバシー",
    },
    "ko": {
        "name": "TraceFence Sentinel",
        "subtitle": "원격 Agent 제어",
        "promotionalText": "Mac의 AI Agent 작업을 모니터링하고 승인과 지원 세션을 iPhone에서 제어하세요.",
        "description": """TraceFence Sentinel은 Mac에서 실행되는 AI Agent를 위한 개인용 iPhone 제어 콘솔입니다.

사용자 소유의 TraceFence Mac 앱과 직접 페어링해 프로젝트, 세션, 최근 대화 맥락과 권한 요청을 확인할 수 있습니다. 지원되는 런타임에서는 지시 전송, 일시 정지, 재개, 인계와 종료도 가능합니다.

TraceFence 계정, 클라우드 릴레이, 광고, 추적 또는 타사 분석을 사용하지 않습니다. 같은 LAN에서는 직접 연결하며, 원격 연결에는 사용자가 별도로 구성한 기존 사설 네트워크를 사용할 수 있습니다.

실제 모니터링과 제어에는 TraceFence Mac 앱이 필요합니다. 페어링 전에는 내장된 읽기 전용 데모를 사용할 수 있습니다.""",
        "keywords": "AI Agent,Mac,Codex,Claude,원격제어,승인,모니터링,세션,개발자,개인정보",
    },
}


def b64url(value: bytes) -> str:
    return base64.urlsafe_b64encode(value).rstrip(b"=").decode()


def token(key_path: Path) -> str:
    key = serialization.load_pem_private_key(key_path.read_bytes(), password=None)
    now = int(time.time())
    header = {"alg": "ES256", "kid": KEY_ID, "typ": "JWT"}
    claims = {"iss": ISSUER_ID, "iat": now, "exp": now + 1200, "aud": "appstoreconnect-v1"}
    message = f"{b64url(json.dumps(header, separators=(',', ':')).encode())}.{b64url(json.dumps(claims, separators=(',', ':')).encode())}".encode()
    signature = key.sign(message, ec.ECDSA(hashes.SHA256()))
    r_value, s_value = utils.decode_dss_signature(signature)
    return f"{message.decode()}.{b64url(r_value.to_bytes(32, 'big') + s_value.to_bytes(32, 'big'))}"


class ASC:
    def __init__(self, key_path: Path) -> None:
        self.key_path = key_path
        self.base = "https://api.appstoreconnect.apple.com/v1"
        self.session = requests.Session()
        self.refresh()

    def refresh(self) -> None:
        self.session.headers.update({"Authorization": f"Bearer {token(self.key_path)}", "Content-Type": "application/json"})

    def json(self, method: str, path: str, ok: tuple[int, ...] = (200, 201, 204), **kwargs: Any) -> dict[str, Any]:
        for attempt in range(6):
            response = self.session.request(method, self.base + path, timeout=180, **kwargs)
            if response.status_code == 401 and attempt == 0:
                self.refresh()
                continue
            if response.status_code == 429 and attempt < 5:
                time.sleep(max(float(response.headers.get("Retry-After", "1")), 1))
                continue
            if response.status_code not in ok:
                raise RuntimeError(f"{method} {path} -> {response.status_code}: {response.text[:2000]}")
            return response.json() if response.text else {}
        raise RuntimeError(f"{method} {path} exhausted retries")


def body(resource_type: str, resource_id: str | None = None, attributes: dict[str, Any] | None = None, relationships: dict[str, Any] | None = None) -> dict[str, Any]:
    data: dict[str, Any] = {"type": resource_type}
    if resource_id: data["id"] = resource_id
    if attributes is not None: data["attributes"] = attributes
    if relationships is not None: data["relationships"] = relationships
    return {"data": data}


def rel(resource_type: str, resource_id: str) -> dict[str, Any]:
    return {"data": {"type": resource_type, "id": resource_id}}


def first(api: ASC, path: str, params: dict[str, Any] | None = None) -> dict[str, Any]:
    items = api.json("GET", path, params=params or {}).get("data") or []
    if not items: raise RuntimeError(f"No resource at {path}")
    return items[0]


def resources(api: ASC) -> tuple[str, str, str]:
    version = next((item for item in api.json("GET", f"/apps/{APP_ID}/appStoreVersions", params={"filter[platform]": "IOS", "limit": 50})["data"] if item["attributes"].get("versionString") == VERSION), None)
    if not version: raise RuntimeError(f"Missing iOS version {VERSION}")
    info = first(api, f"/apps/{APP_ID}/appInfos", {"limit": 10})
    deadline = time.time() + 1200
    while True:
        builds = api.json("GET", "/builds", params={"filter[app]": APP_ID, "filter[version]": BUILD, "limit": 20})["data"]
        valid = [item for item in builds if item["attributes"].get("processingState") == "VALID"]
        if valid: return version["id"], info["id"], valid[0]["id"]
        if time.time() >= deadline: raise RuntimeError(f"Build {BUILD} did not become VALID")
        state = builds[0]["attributes"].get("processingState") if builds else "missing"
        print(f"Waiting for build {BUILD}: {state}", flush=True)
        time.sleep(30)


def localization_ids(api: ASC, path: str) -> dict[str, str]:
    return {item["attributes"]["locale"]: item["id"] for item in api.json("GET", path, params={"limit": 100})["data"]}


def upsert_localization(api: ASC, locale: str, resource_type: str, collection_path: str, parent_path: str,
                        relationship_name: str, parent_resource_type: str, parent_id: str,
                        attributes: dict[str, Any]) -> str:
    ids = localization_ids(api, parent_path)
    if locale in ids:
        resource_id = ids[locale]
        api.json("PATCH", f"/{resource_type}/{resource_id}", json=body(resource_type, resource_id, attributes))
        return resource_id

    try:
        created = api.json(
            "POST", collection_path, ok=(201,),
            json=body(resource_type, attributes={"locale": locale, **attributes},
                      relationships={relationship_name: rel(parent_resource_type, parent_id)}),
        )
        return created["data"]["id"]
    except RuntimeError as error:
        if "ATTRIBUTE.INVALID.DUPLICATE" not in str(error):
            raise
        ids = localization_ids(api, parent_path)
        if locale not in ids:
            raise
        resource_id = ids[locale]
        api.json("PATCH", f"/{resource_type}/{resource_id}", json=body(resource_type, resource_id, attributes))
        return resource_id


def sync_localizations(api: ASC, version_id: str, info_id: str) -> str:
    version_ids: dict[str, str] = {}
    for locale, values in LOCALES.items():
        attrs = {"name": values["name"], "subtitle": values["subtitle"], "privacyPolicyUrl": PRIVACY_URL, "privacyChoicesUrl": None}
        upsert_localization(api, locale, "appInfoLocalizations", "/appInfoLocalizations",
                            f"/appInfos/{info_id}/appInfoLocalizations", "appInfo", "appInfos", info_id, attrs)

        attrs = {"description": values["description"], "keywords": values["keywords"], "promotionalText": values["promotionalText"], "supportUrl": SUPPORT_URL, "marketingUrl": None}
        version_ids[locale] = upsert_localization(
            api, locale, "appStoreVersionLocalizations", "/appStoreVersionLocalizations",
            f"/appStoreVersions/{version_id}/appStoreVersionLocalizations",
            "appStoreVersion", "appStoreVersions", version_id, attrs,
        )
        print(f"Synced {locale}")
    return version_ids["en-US"]


def sync_version(api: ASC, version_id: str, info_id: str, build_id: str) -> None:
    api.json("PATCH", f"/apps/{APP_ID}", json=body("apps", APP_ID, {"contentRightsDeclaration": "DOES_NOT_USE_THIRD_PARTY_CONTENT"}))
    api.json("PATCH", f"/appInfos/{info_id}", json=body("appInfos", info_id, relationships={"primaryCategory": rel("appCategories", "DEVELOPER_TOOLS"), "secondaryCategory": rel("appCategories", "UTILITIES")}))
    api.json("PATCH", f"/appStoreVersions/{version_id}", json=body("appStoreVersions", version_id, {"copyright": "2026 AI-Scarlett", "releaseType": "AFTER_APPROVAL", "usesIdfa": False}, {"build": rel("builds", build_id)}))

    rating = api.json("GET", f"/appInfos/{info_id}/ageRatingDeclaration")["data"]
    rating_attrs = {
        "advertising": False, "alcoholTobaccoOrDrugUseOrReferences": "NONE", "contests": "NONE", "gambling": False,
        "gamblingSimulated": "NONE", "gunsOrOtherWeapons": "NONE", "healthOrWellnessTopics": False, "lootBox": False,
        "medicalOrTreatmentInformation": "NONE", "messagingAndChat": False, "parentalControls": False,
        "profanityOrCrudeHumor": "NONE", "ageAssurance": False, "sexualContentGraphicAndNudity": "NONE",
        "sexualContentOrNudity": "NONE", "horrorOrFearThemes": "NONE", "matureOrSuggestiveThemes": "NONE",
        "unrestrictedWebAccess": False, "userGeneratedContent": False, "violenceCartoonOrFantasy": "NONE",
        "violenceRealisticProlongedGraphicOrSadistic": "NONE", "violenceRealistic": "NONE", "ageRatingOverrideV2": "NONE",
        "koreaAgeRatingOverride": "NONE", "developerAgeRatingInfoUrl": None,
    }
    api.json("PATCH", f"/ageRatingDeclarations/{rating['id']}", json=body("ageRatingDeclarations", rating["id"], rating_attrs))

    review = api.json("GET", f"/appStoreVersions/{version_id}/appStoreReviewDetail")["data"]
    review_attrs = {
        "contactFirstName": "Zhou", "contactLastName": "Xiaoming", "contactPhone": "15827658181",
        "contactEmail": "76462245@qq.com", "demoAccountRequired": False, "demoAccountName": None,
        "demoAccountPassword": None, "notes": REVIEW_NOTES,
    }
    if review:
        api.json("PATCH", f"/appStoreReviewDetails/{review['id']}", json=body("appStoreReviewDetails", review["id"], review_attrs))
    else:
        api.json("POST", "/appStoreReviewDetails", ok=(201,), json=body("appStoreReviewDetails", attributes=review_attrs, relationships={"appStoreVersion": rel("appStoreVersions", version_id)}))


def ensure_free_pricing(api: ASC) -> None:
    try:
        current_prices = api.json(
            "GET", f"/appPriceSchedules/{APP_ID}/manualPrices", params={"limit": 200}
        )["data"]
        if current_prices:
            print("Free app pricing already configured")
            return
    except RuntimeError as error:
        if "-> 404:" not in str(error):
            raise

    points = api.json(
        "GET", f"/apps/{APP_ID}/appPricePoints",
        params={"filter[territory]": "USA", "include": "territory", "limit": 200},
    )["data"]
    free_point = next(
        (item for item in points if float(item["attributes"].get("customerPrice") or -1) == 0),
        None,
    )
    if free_point is None:
        raise RuntimeError("No free USA app price point is available")
    placeholder = "${freeprice-0}"
    payload = body(
        "appPriceSchedules", attributes={},
        relationships={
            "app": rel("apps", APP_ID),
            "manualPrices": {"data": [{"type": "appPrices", "id": placeholder}]},
            "baseTerritory": rel("territories", "USA"),
        },
    )
    payload["included"] = [{
        "type": "appPrices",
        "id": placeholder,
        "attributes": {"startDate": None, "endDate": None},
        "relationships": {"appPricePoint": rel("appPricePoints", free_point["id"])},
    }]
    try:
        api.json("POST", "/appPriceSchedules", ok=(201,), json=payload)
        print("Configured the iOS app as free")
    except RuntimeError as error:
        if "PRICE_ALREADY_EXISTS" in str(error) or "already exists" in str(error).lower():
            print("Free app pricing already configured")
            return
        raise


def screenshot_set(api: ASC, localization_id: str) -> str:
    sets = api.json("GET", f"/appStoreVersionLocalizations/{localization_id}/appScreenshotSets", params={"limit": 50})["data"]
    match = next((item for item in sets if item["attributes"].get("screenshotDisplayType") == "APP_IPHONE_67"), None)
    if match: return match["id"]
    created = api.json("POST", "/appScreenshotSets", ok=(201,), json=body("appScreenshotSets", attributes={"screenshotDisplayType": "APP_IPHONE_67"}, relationships={"appStoreVersionLocalization": rel("appStoreVersionLocalizations", localization_id)}))
    return created["data"]["id"]


def upload_screenshots(api: ASC, localization_id: str) -> None:
    files = sorted(SCREENSHOT_DIR.glob("*.png"))
    if len(files) != 5: raise RuntimeError(f"Expected 5 screenshots in {SCREENSHOT_DIR}, found {len(files)}")
    set_id = screenshot_set(api, localization_id)
    for item in api.json("GET", f"/appScreenshotSets/{set_id}/appScreenshots", params={"limit": 50})["data"]:
        api.json("DELETE", f"/appScreenshots/{item['id']}")
    for path in files:
        data = path.read_bytes()
        created = api.json("POST", "/appScreenshots", ok=(201,), json=body("appScreenshots", attributes={"fileName": path.name, "fileSize": len(data)}, relationships={"appScreenshotSet": rel("appScreenshotSets", set_id)}))
        screenshot_id = created["data"]["id"]
        for operation in created["data"]["attributes"].get("uploadOperations") or []:
            offset = int(operation.get("offset") or 0)
            length = int(operation.get("length") or len(data))
            headers = {header["name"]: header["value"] for header in operation.get("requestHeaders", [])}
            response = requests.request(operation["method"], operation["url"], headers=headers, data=data[offset:offset + length], timeout=180)
            if response.status_code // 100 != 2: raise RuntimeError(f"Screenshot upload failed: {response.status_code} {response.text[:500]}")
        api.json("PATCH", f"/appScreenshots/{screenshot_id}", json=body("appScreenshots", screenshot_id, {"sourceFileChecksum": hashlib.md5(data).hexdigest(), "uploaded": True}))
        print(f"Uploaded {path.name}")


def submit(api: ASC, version_id: str) -> None:
    existing = api.json("GET", "/reviewSubmissions", params={"filter[app]": APP_ID, "filter[platform]": "IOS", "limit": 20})["data"]
    submission = next((item for item in existing if item["attributes"].get("state") in {"READY_FOR_REVIEW", "UNRESOLVED_ISSUES"}), None)
    if not submission:
        submission = api.json("POST", "/reviewSubmissions", ok=(201,), json=body("reviewSubmissions", attributes={"platform": "IOS"}, relationships={"app": rel("apps", APP_ID)}))["data"]
    items = api.json("GET", f"/reviewSubmissions/{submission['id']}/items", params={"limit": 100})["data"]
    if not any(item.get("relationships", {}).get("appStoreVersion", {}).get("data", {}).get("id") == version_id for item in items):
        api.json("POST", "/reviewSubmissionItems", ok=(201,), json=body("reviewSubmissionItems", relationships={"reviewSubmission": rel("reviewSubmissions", submission["id"]), "appStoreVersion": rel("appStoreVersions", version_id)}))
    result = api.json("PATCH", f"/reviewSubmissions/{submission['id']}", json=body("reviewSubmissions", submission["id"], {"submitted": True}))["data"]
    print(f"Submitted review {result['id']}: {result['attributes'].get('state')}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--skip-screenshots", action="store_true")
    parser.add_argument("--submit", action="store_true")
    args = parser.parse_args()
    key_path = Path.home() / f".appstoreconnect/private_keys/AuthKey_{KEY_ID}.p8"
    if not key_path.exists():
        print(f"Missing API key: {key_path}", file=sys.stderr)
        return 2
    api = ASC(key_path)
    version_id, info_id, build_id = resources(api)
    print(f"Resolved version={version_id} build={build_id}")
    en_localization_id = sync_localizations(api, version_id, info_id)
    sync_version(api, version_id, info_id, build_id)
    ensure_free_pricing(api)
    if not args.skip_screenshots: upload_screenshots(api, en_localization_id)
    if args.submit: submit(api, version_id)
    print("App Privacy answers must be verified in App Store Connect before submission.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
